---
title: "About the project"
description: |
  How we got started
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Sunday Service is a community bicycle repair project.
It grew out of informal bike repair sessions that have variously been called 'bike repair Sundays', 'bike fix Sundays' and just 'fixing bikes on the street', which is in essence what it's about:
people who have tools and knowhow getting bikes in need of some attention back on the road to help people in the local community.

The name Sunday Service was coined after the concept was formalised.
A local charity in Leeds provided space for regular bike repair activities (every Sunday), a meeting was organised, and Sunday Service was the name that stuck.

Sunday service isn't about doing major bike repairs.
It's about providing space and time for people to learn how to service and make minor repairs to their own bike.
The first Sunday Service sessions in Leeds ran 2pm to 5pm on Sundays and were attended by 2 people with experience fixing bikes and 5-10 people who wanted to fix their bikes or learn bike repair skills.

Although the project started in Leeds, inspired by the [Pedallers Arms](https://pedallers-arms.org/) cooperative project and with support from the [Latch](https://www.latch.org.uk/) community housing charity, the concept can work anywhere.
All you need to make a Sunday Service event happen near your are:

- People who need to service or make minor repairs to their bike
- People with basic bike fixing knowledge
- Basic tools and components (e.g. puncture repair kit, bike pump)
- A safe space to work

That's it.
A person fixing their own bike on the street in a public space could be a Sunday service.
You don't even need to do it on a Sunday!

Taking some steps to formalise the idea as a regular event can help it grow and benefit more people, which is what this website is about.
